spring:
  application:
    name: demo
  mongodb:
    host: localhost
    port: 27017
    database: dungeon
    username: dev
    password: dev
    representation:
      uuid: standard

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%h %l %u %t \"%r\" %s %b %D"
      directory: /dev
      prefix: stdout
      suffix: ""
      file-date-format: ""
      rotate: false
      buffered: false

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
